source "http://rubygems.org"

# service
gem 'activerecord', "6.1.7.1"
gem 'sqlite3', "=0.1.1"
gem 'sinatra', "=1.1.0"

# client
gem 'json', '=1.4.6'
gem 'typhoeus', '=0.2.0'

# testing
gem 'rspec', '=2.2.0'
gem 'rack-test', '=0.5.6'
